version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: colemamd/zoneminder:latest
        restart: unless-stopped
        ports:
            - 443:443/tcp
            - 9000:9000/tcp
        network_mode: "bridge"
        privileged: true
        environment:
            - TZ=America/New_York
            - SHMEM=50%
            - PUID=99
            - PGID=100
            - INSTALL_HOOK=0
            - INSTALL_FACE=0
            - INSTALL_TINY_YOLO=0
            - INSTALL_YOLO=0
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - /docker/zoneminder:/config:rw
            - /cctv:/var/cache/zoneminder:rw
            - /etc/zm/ssl:/ssl:ro
