name: Docker Image CI

on:
  push:
    branches: 
      - master

    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Build the Docker image
      run: docker buildx build .  --file Dockerfile --tag colemamd/zoneminder:latest --platform linux/armhf --output "type=image,push=false"
    - name: Publish to Docker
      uses: zenato/docker-action@master
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: colemamd/zoneminder
        tag: 1.0
